# Generated by Django 5.0.2 on 2024-03-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
